dev/main/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.utils.translation import gettext_lazy as _

urlpatterns = [
    # Main.
    path("admin/", admin.site.urls),
    path("", include("parea.urls", namespace="parea")),
    path("rarea/", include("rarea.urls", namespace="rarea")),
    # Core.
    path("auth/", include("core.uauth.urls", namespace="core/uauth")),
    # Modules.
    path("demo/", include("modules.demo.urls", namespace="modules/demo")),
    # Solar
    path("solar/", include("modules.solar.urls", namespace="modules/solar")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = _("ADMIN_AREA_TITLE")

dev/rarea/urls.py
from django.urls import path

from . import views

app_name = "rarea"


urlpatterns = [
    path("", views.RNotesView.as_view(module="rarea"), name="index"),
    path("ui-guidelines", views.UIGuidelinesView.as_view(), name="ui-guidelines"),
]

dev/rarea/models.py
# Create your models here.

dev/rarea/views/rarea_rnotes_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class RNotesView(LoginRequiredMixin, TemplateView):
    template_name = "rarea/rnotes.html"
    module = "rarea"

dev/rarea/views/rarea_ui_guidelines_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class UIGuidelinesView(LoginRequiredMixin, TemplateView):
    template_name = "rarea/ui_guidelines.html"

dev/rarea/templates/rarea/footer.html
{% load i18n %}

<div class="footer">
    (C) {% now "Y" %} Indeform Ltd.
</div>

dev/rarea/templates/rarea/header.html
{% load i18n %}

<div class="header">
    <ul class="wbar">
        <li class="logo"></li>
        <li class="user">
            <form method="post" action="{% url 'core/uauth:logout' %}">
                {% csrf_token %}
                <button type="submit"> Logout </button>
            </form>
        </li>
    </ul>
</div>

<ul class="nav">
    {% include request.resolver_match.namespace|add:"/menu.html"|default:"rarea/menu.html" %}
</ul>

dev/rarea/templates/rarea/layout.html
{% load i18n %}
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title> Indeform OSOM.Codex (Sandbox edition) </title>
        <link rel="stylesheet" type="text/css" href="{% static 'rarea/build.css' %}" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <meta charset="UTF-8"/>
        <meta name="description" content="Indeform OSOM.Codex (Sandbox edition)"/>
        <meta name="keywords" content=""/>
        <meta name="author" content="(C) Indeform Ltd."/>
    </head>

    <body>
        {% include 'rarea/header.html' %}

        <ul class="sbarnav">
            <li><a href="{% url 'rarea:index' %}"> Home </a></li>
            <li><a href="{% url 'modules/demo:data' %}"> Demo </a></li>
            <li><a>...</a></li>
        </ul>

        <div class="content">
            {% block content %}{% endblock content %}
        </div>

        {% include 'rarea/footer.html' %}
        <script type="text/javascript" src="{% static 'shared/build.js' %}"></script>
        <script type="text/javascript" src="{% static 'rarea/build.js' %}"></script>
    </body>
</html>

dev/rarea/templates/rarea/layoutnp.html
{% load i18n %}
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Indeform OSOM.Codex (Sandbox edition) </title>
        <link rel="stylesheet" type="text/css" href="{% static 'rarea/build.css' %}" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <meta charset="UTF-8"/>
        <meta name="description" content="Indeform OSOM.Codex (Sandbox edition)"/>
        <meta name="keywords" content=""/>
        <meta name="author" content="(C) Indeform Ltd."/>
    </head>

    <body>
        {% include 'rarea/header.html' %}

        <ul class="sbarnav">
            <li><a href="{% url 'rarea:index' %}">Home</a></li>
            <li><a href="{% url 'modules/demo:data' %}">Demo</a></li>
            <li><a>...</a></li>
        </ul>
        <div class="content nopadd">
            {% block content %}{% endblock content %}
        </div>

        {% include 'rarea/footer.html' %}
        <script type="text/javascript" src="{% static 'shared/build.js' %}"></script>
        <script type="text/javascript" src="{% static 'rarea/build.js' %}"></script>
    </body>
</html>

dev/rarea/templates/rarea/menu.html
{% load i18n %}

<li><a class="current" href="javascript:void();">Home</a></li>
<li><a href="{% url 'rarea:index' %}">Dashboard</a></li>
<li><a href="{% url 'rarea:ui-guidelines' %}">UI guidelines</a></li>

dev/rarea/templates/rarea/rnotes.html
{% extends 'rarea/layout.html' %}
{% load i18n %}

{% block content %}
    <h1 class="con-header">Welcome to the OSOM.Codex sandbox edition!</h1>
    <p class="con-header">
        Great job! You already did the very first step - initialized and set your project environment. 
        Please feel free to explore what you can do next.
    </p>

    <h2 class="con-header">TODO NEXT:</h2>
    <ul class="dash">
        <li>Start exploring "dev/parea" and "dev/rarea" to learn more about code/folders structure you should follow for "Areas".</li>
        <li>Start exploring <a href="/demo/data">"Demo -> Data"</a> and <a href="/demo/cad">"Demo -> CAD"</a> at "dev/modules" to learn more about code/folders structure you should follow wile creating "Modules".</li>
        <li>Explore <a href="/rarea/ui-guidelines">UI guidelines</a> code at "dev/rarea/templates/ui_guidelines.html" to learn how to form standard forms and views.</li>
        <li>Got it? So it's time to start creating your own module at "dev/modules"! Good luck!</li>
    </ul>

    <h2 class="con-header">RELEASES</h2>
    <h2 class="con-header">osom.codex.current</h2>
    <ul class="dash">
        <li>Updated modules and descriptions.</li>
    </ul>

    <h2 class="con-header">osom.codex.r1.0.202202-01</h2>
    <ul class="dash">
        <li>Initial sandbox version.</li>
    </ul>
{% endblock %}

dev/rarea/templates/rarea/ui_guidelines.html
{% extends 'rarea/layout.html' %}
{% load i18n %}
{% load static %}

{% block content %}
    <h1 class="con-header">UI Guidelines</h1>

    <div class="col2 gap">
        <!-- 1 Column form layout -->
        <form class="col1" method="">
            <h2>Form (col1)</h2>
            <p>
                <label for="text_field">Text field</label>
                <input id="text_field" type="text" value="Value">
                {% if 1 %}<span class="error">Error message. This is very long error message which does not fit into single line.</span>{% endif %}
            </p>
            <p>
                <label for="dropdown_field">Dropdown field</label>
                <select id="dropdown_field">
                    <option value="1">value 1</option>
                    <option value="2">value 2</option>
                    <option value="3">value 3</option>
                </select>
                {% if 1 %}<span class="error">Error message</span>{% endif %}
            </p>
            <p>
                <label for="button_field">Button field</label>
                <button value="rb">Button</button>
                {% if 1 %}<span class="error">Error message</span>{% endif %}
            </p>
        </form>

        <!-- 2 Column Form layout -->
        <form class="col2" method="">
            <h2 class="fill2">Form (col2)</h2>
            <p>
                <label for="text_field">Text field</label>
                <input id="text_field" type="text" value="Value">
                {% if 1 %}<span class="error">Error message. This is very long error message which does not fit into single line.</span>{% endif %}
            </p>
            <p>
                <label for="dropdown_field">Dropdown field</label>
                <select id="dropdown_field">
                    <option value="1">value 1</option>
                    <option value="2">value 2</option>
                    <option value="3">value 3</option>
                </select>
                {% if 1 %}<span class="error">Error message</span>{% endif %}
            </p>
            <p>
                <input id="checkbox_field" type="checkbox" value="cb">Checkbox field
                {% if 1 %}<span class="error">Error message</span>{% endif %}
            </p>
            <p>
                <input id="radio_field" type="radio" value="rb"/>Radio field
                {% if 1 %}<span class="error">Error message</span>{% endif %}
            </p>
            <p class="fill2">
                <label for="textarea_field">Textarea</label>
                <textarea id="textarea_field"></textarea>
                {% if 1 %}<span class="error">Error message</span>{% endif %}
            </p>
            <p>
                <label for="button_field">Button field</label>
                <button value="rb">Button</button>
                {% if 1 %}<span class="error">Error message</span>{% endif %}
            </p>
            <p>
                <label for="list_field">List field:</label>
                <select id="list_field" multiple>
                    <option value="1">value 1</option>
                    <option value="2">value 2</option>
                    <option value="3">value 3</option>
                </select>
                {% if 1 %}<span class="error">Error message</span>{% endif %}
            </p>
        </form>


        <!-- 3 Column form layout -->
        <form class="col3" method="">
            <h2 class="fill3">Form (col3)</h2>
            <p class="fill2">
                <label for="text_field">Text field</label>
                <input id="text_field" type="text" value="Value">
                <span class="error">Error message. This is very long error message which does not fit into single line.</span>
            </p>
            <p>
                <label for="dropdown_field">Dropdown field</label>
                <select id="dropdown_field">
                    <option value="1">value 1</option>
                    <option value="2">value 2</option>
                    <option value="3">value 3</option>
                </select>
                {% if 1 %}<span class="error">Error message</span>{% endif %}
            </p>
            <p>
                <input id="checkbox_field" type="checkbox" value="cb">Checkbox field
                {% if 1 %}<span class="error">Error message</span>{% endif %}
            </p>
            <p>
                <input id="radio_field" type="radio" value="rb"/>Radio field
                {% if 1 %}<span class="error">Error message</span>{% endif %}
            </p>
            <p class="fill3">
                <label for="textarea_field">Textarea</label>
                <textarea id="textarea_field"></textarea>
                {% if 1 %}<span class="error">Error message</span>{% endif %}
            </p>
            <p class="fill2">
                <label for="button_field">Button field</label>
                <button value="rb">Button</button>
                {% if 1 %}<span class="error">Error message</span>{% endif %}
            </p>
            <p>
                <label for="list_field">List field:</label>
                <select id="list_field" multiple>
                    <option value="1">value 1</option>
                    <option value="2">value 2</option>
                    <option value="3">value 3</option>
                </select>
                {% if 1 %}<span class="error">Error message</span>{% endif %}
            </p>
        </form>

        <!-- Table layout -->
        <table>
            <caption>Table</caption>
            <thead>
                <tr>
                    <th>Items</th>
                    <th>Count</th>
                    <th>Unit price</th>
                    <th>Total price</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Monitor</td>
                    <td>5</td>
                    <td>100.00</td>
                    <td class="tright">500.00</td>
                </tr>
                <tr>
                    <td>PC case</td>
                    <td>2</td>
                    <td>70.00</td>
                    <td class="tright">140.00</td>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock %}